image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      git clone https://github.com/rbenv/rbenv.git ~/.rbenv && \
      git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build && \
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile && \
      ~/.rbenv/bin/rbenv init
      echo 'eval "$(rbenv init -)"' >> ~/.bash_profile && \
      source ~/.bash_profile && \
      rbenv install && \
      gem install bundler && \
      bundle install
